<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [1]:
#!pip install pandas
#!pip install matplotlib

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [2]:
# Import necessary libraries
import pandas as pd

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
print(df.head())

   ResponseId                      MainBranch                 Age  \
0           1  I am a developer by profession  Under 18 years old
1           2  I am a developer by profession     35-44 years old
2           3  I am a developer by profession     45-54 years old
3           4           I am learning to code     18-24 years old
4           5  I am a developer by profession     18-24 years old

            Employment RemoteWork   Check  \
0  Employed, full-time     Remote  Apples
1  Employed, full-time     Remote  Apples
2  Employed, full-time     Remote  Apples
3   Student, full-time        NaN  Apples
4   Student, full-time        NaN  Apples

                                    CodingActivities  \
0                                              Hobby
1  Hobby;Contribute to open-source projects;Other...
2  Hobby;Contribute to open-source projects;Other...
3                                                NaN
4                                                NaN

                                             EdLevel  \
0                          Primary/elementary school
1       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3  Some college/university study without earning ...
4  Secondary school (e.g. American high school, G...

                                           LearnCode  \
0                             Books / Physical media
1  Books / Physical media;Colleague;On the job tr...
2  Books / Physical media;Colleague;On the job tr...
3  Other online resources (e.g., videos, blogs, f...
4  Other online resources (e.g., videos, blogs, f...

                                     LearnCodeOnline  ... JobSatPoints_6  \
0                                                NaN  ...            NaN
1  Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3  Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4  Technical documentation;Blogs;Written Tutorial...  ...            NaN

  JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0            NaN            NaN            NaN             NaN
1            0.0            0.0            0.0             0.0
2            NaN            NaN            NaN             NaN
3            NaN            NaN            NaN             NaN
4            NaN            NaN            NaN             NaN

  JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly JobSat
0             NaN                    NaN        NaN                 NaN    NaN
1             0.0                    NaN        NaN                 NaN    NaN
2             NaN  Appropriate in length       Easy                 NaN    NaN
3             NaN               Too long       Easy                 NaN    NaN
4             NaN              Too short       Easy                 NaN    NaN

[5 rows x 114 columns]

In [3]:
import numpy as np

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [4]:
missing_values = df.isnull()
df_columns = df.columns.values.tolist()
for column in df_columns:
    print(column)
    print('type: ', df[column].dtypes, '  count: ', df[column].count(), '  missing values:', missing_values[column].sum(), '  % of missing values: ', 
          f'{(missing_values[column].sum() / len(df.index)) * 100: .2f}%', '\n')

ResponseId
type:  int64   count:  65437   missing values: 0   % of missing values:   0.00%

MainBranch
type:  object   count:  65437   missing values: 0   % of missing values:   0.00%

Age
type:  object   count:  65437   missing values: 0   % of missing values:   0.00%

Employment
type:  object   count:  65437   missing values: 0   % of missing values:   0.00%

RemoteWork
type:  object   count:  54806   missing values: 10631   % of missing values:   16.25%

Check
type:  object   count:  65437   missing values: 0   % of missing values:   0.00%

CodingActivities
type:  object   count:  54466   missing values: 10971   % of missing values:   16.77%

EdLevel
type:  object   count:  60784   missing values: 4653   % of missing values:   7.11%

LearnCode
type:  object   count:  60488   missing values: 4949   % of missing values:   7.56%

LearnCodeOnline
type:  object   count:  49237   missing values: 16200   % of missing values:   24.76%

TechDoc
type:  object   count:  40897   missing values: 24540   % of missing values:   37.50%

YearsCode
type:  object   count:  59869   missing values: 5568   % of missing values:   8.51%

YearsCodePro
type:  object   count:  51610   missing values: 13827   % of missing values:   21.13%

DevType
type:  object   count:  59445   missing values: 5992   % of missing values:   9.16%

OrgSize
type:  object   count:  47480   missing values: 17957   % of missing values:   27.44%

PurchaseInfluence
type:  object   count:  47406   missing values: 18031   % of missing values:   27.55%

BuyNewTool
type:  object   count:  45181   missing values: 20256   % of missing values:   30.95%

BuildvsBuy
type:  object   count:  43358   missing values: 22079   % of missing values:   33.74%

TechEndorse
type:  object   count:  43668   missing values: 21769   % of missing values:   33.27%

Country
type:  object   count:  58930   missing values: 6507   % of missing values:   9.94%

Currency
type:  object   count:  46684   missing values: 18753   % of missing values:   28.66%

CompTotal
type:  float64   count:  33740   missing values: 31697   % of missing values:   48.44%

LanguageHaveWorkedWith
type:  object   count:  59745   missing values: 5692   % of missing values:   8.70%

LanguageWantToWorkWith
type:  object   count:  55752   missing values: 9685   % of missing values:   14.80%

LanguageAdmired
type:  object   count:  50872   missing values: 14565   % of missing values:   22.26%

DatabaseHaveWorkedWith
type:  object   count:  50254   missing values: 15183   % of missing values:   23.20%

DatabaseWantToWorkWith
type:  object   count:  42558   missing values: 22879   % of missing values:   34.96%

DatabaseAdmired
type:  object   count:  38557   missing values: 26880   % of missing values:   41.08%

PlatformHaveWorkedWith
type:  object   count:  42366   missing values: 23071   % of missing values:   35.26%

PlatformWantToWorkWith
type:  object   count:  34532   missing values: 30905   % of missing values:   47.23%

PlatformAdmired
type:  object   count:  31377   missing values: 34060   % of missing values:   52.05%

WebframeHaveWorkedWith
type:  object   count:  45161   missing values: 20276   % of missing values:   30.99%

WebframeWantToWorkWith
type:  object   count:  38535   missing values: 26902   % of missing values:   41.11%

WebframeAdmired
type:  object   count:  34943   missing values: 30494   % of missing values:   46.60%

EmbeddedHaveWorkedWith
type:  object   count:  22214   missing values: 43223   % of missing values:   66.05%

EmbeddedWantToWorkWith
type:  object   count:  17600   missing values: 47837   % of missing values:   73.10%

EmbeddedAdmired
type:  object   count:  16733   missing values: 48704   % of missing values:   74.43%

MiscTechHaveWorkedWith
type:  object   count:  39443   missing values: 25994   % of missing values:   39.72%

MiscTechWantToWorkWith
type:  object   count:  32964   missing values: 32473   % of missing values:   49.62%

MiscTechAdmired
type:  object   count:  29596   missing values: 35841   % of missing values:   54.77%

ToolsTechHaveWorkedWith
type:  object   count:  52482   missing values: 12955   % of missing values:   19.80%

ToolsTechWantToWorkWith
type:  object   count:  46084   missing values: 19353   % of missing values:   29.58%

ToolsTechAdmired
type:  object   count:  43997   missing values: 21440   % of missing values:   32.76%

NEWCollabToolsHaveWorkedWith
type:  object   count:  57592   missing values: 7845   % of missing values:   11.99%

NEWCollabToolsWantToWorkWith
type:  object   count:  52087   missing values: 13350   % of missing values:   20.40%

NEWCollabToolsAdmired
type:  object   count:  50711   missing values: 14726   % of missing values:   22.50%

OpSysPersonal use
type:  object   count:  58174   missing values: 7263   % of missing values:   11.10%

OpSysProfessional use
type:  object   count:  52973   missing values: 12464   % of missing values:   19.05%

OfficeStackAsyncHaveWorkedWith
type:  object   count:  48093   missing values: 17344   % of missing values:   26.50%

OfficeStackAsyncWantToWorkWith
type:  object   count:  38966   missing values: 26471   % of missing values:   40.45%

OfficeStackAsyncAdmired
type:  object   count:  37204   missing values: 28233   % of missing values:   43.15%

OfficeStackSyncHaveWorkedWith
type:  object   count:  55545   missing values: 9892   % of missing values:   15.12%

OfficeStackSyncWantToWorkWith
type:  object   count:  46711   missing values: 18726   % of missing values:   28.62%

OfficeStackSyncAdmired
type:  object   count:  44712   missing values: 20725   % of missing values:   31.67%

AISearchDevHaveWorkedWith
type:  object   count:  44453   missing values: 20984   % of missing values:   32.07%

AISearchDevWantToWorkWith
type:  object   count:  36701   missing values: 28736   % of missing values:   43.91%

AISearchDevAdmired
type:  object   count:  35543   missing values: 29894   % of missing values:   45.68%

NEWSOSites
type:  object   count:  60286   missing values: 5151   % of missing values:   7.87%

SOVisitFreq
type:  object   count:  59536   missing values: 5901   % of missing values:   9.02%

SOAccount
type:  object   count:  59560   missing values: 5877   % of missing values:   8.98%

SOPartFreq
type:  object   count:  45237   missing values: 20200   % of missing values:   30.87%

SOHow
type:  object   count:  58962   missing values: 6475   % of missing values:   9.90%

SOComm
type:  object   count:  59163   missing values: 6274   % of missing values:   9.59%

AISelect
type:  object   count:  60907   missing values: 4530   % of missing values:   6.92%

AISent
type:  object   count:  45873   missing values: 19564   % of missing values:   29.90%

AIBen
type:  object   count:  36894   missing values: 28543   % of missing values:   43.62%

AIAcc
type:  object   count:  37302   missing values: 28135   % of missing values:   43.00%

AIComplex
type:  object   count:  37021   missing values: 28416   % of missing values:   43.42%

AIToolCurrently Using
type:  object   count:  35072   missing values: 30365   % of missing values:   46.40%

AIToolInterested in Using
type:  object   count:  30691   missing values: 34746   % of missing values:   53.10%

AIToolNot interested in Using
type:  object   count:  24414   missing values: 41023   % of missing values:   62.69%

AINextMuch more integrated
type:  object   count:  13438   missing values: 51999   % of missing values:   79.46%

AINextNo change
type:  object   count:  12498   missing values: 52939   % of missing values:   80.90%

AINextMore integrated
type:  object   count:  24428   missing values: 41009   % of missing values:   62.67%

AINextLess integrated
type:  object   count:  2355   missing values: 63082   % of missing values:   96.40%

AINextMuch less integrated
type:  object   count:  1148   missing values: 64289   % of missing values:   98.25%

AIThreat
type:  object   count:  44689   missing values: 20748   % of missing values:   31.71%

AIEthics
type:  object   count:  41548   missing values: 23889   % of missing values:   36.51%

AIChallenges
type:  object   count:  37531   missing values: 27906   % of missing values:   42.65%

TBranch
type:  object   count:  44477   missing values: 20960   % of missing values:   32.03%

ICorPM
type:  object   count:  29801   missing values: 35636   % of missing values:   54.46%

WorkExp
type:  float64   count:  29658   missing values: 35779   % of missing values:   54.68%

Knowledge_1
type:  object   count:  28664   missing values: 36773   % of missing values:   56.20%

Knowledge_2
type:  object   count:  28021   missing values: 37416   % of missing values:   57.18%

Knowledge_3
type:  object   count:  28095   missing values: 37342   % of missing values:   57.07%

Knowledge_4
type:  object   count:  28030   missing values: 37407   % of missing values:   57.16%

Knowledge_5
type:  object   count:  27880   missing values: 37557   % of missing values:   57.39%

Knowledge_6
type:  object   count:  27864   missing values: 37573   % of missing values:   57.42%

Knowledge_7
type:  object   count:  27778   missing values: 37659   % of missing values:   57.55%

Knowledge_8
type:  object   count:  27758   missing values: 37679   % of missing values:   57.58%

Knowledge_9
type:  object   count:  27635   missing values: 37802   % of missing values:   57.77%

Frequency_1
type:  object   count:  28369   missing values: 37068   % of missing values:   56.65%

Frequency_2
type:  object   count:  28364   missing values: 37073   % of missing values:   56.65%

Frequency_3
type:  object   count:  27710   missing values: 37727   % of missing values:   57.65%

TimeSearching
type:  object   count:  28911   missing values: 36526   % of missing values:   55.82%

TimeAnswering
type:  object   count:  28844   missing values: 36593   % of missing values:   55.92%

Frustration
type:  object   count:  28251   missing values: 37186   % of missing values:   56.83%

ProfessionalTech
type:  object   count:  27764   missing values: 37673   % of missing values:   57.57%

ProfessionalCloud
type:  object   count:  28491   missing values: 36946   % of missing values:   56.46%

ProfessionalQuestion
type:  object   count:  28807   missing values: 36630   % of missing values:   55.98%

Industry
type:  object   count:  28858   missing values: 36579   % of missing values:   55.90%

JobSatPoints_1
type:  float64   count:  29324   missing values: 36113   % of missing values:   55.19%

JobSatPoints_4
type:  float64   count:  29393   missing values: 36044   % of missing values:   55.08%

JobSatPoints_5
type:  float64   count:  29411   missing values: 36026   % of missing values:   55.05%

JobSatPoints_6
type:  float64   count:  29450   missing values: 35987   % of missing values:   54.99%

JobSatPoints_7
type:  float64   count:  29448   missing values: 35989   % of missing values:   55.00%

JobSatPoints_8
type:  float64   count:  29456   missing values: 35981   % of missing values:   54.99%

JobSatPoints_9
type:  float64   count:  29456   missing values: 35981   % of missing values:   54.99%

JobSatPoints_10
type:  float64   count:  29450   missing values: 35987   % of missing values:   54.99%

JobSatPoints_11
type:  float64   count:  29445   missing values: 35992   % of missing values:   55.00%

SurveyLength
type:  object   count:  56182   missing values: 9255   % of missing values:   14.14%

SurveyEase
type:  object   count:  56238   missing values: 9199   % of missing values:   14.06%

ConvertedCompYearly
type:  float64   count:  23435   missing values: 42002   % of missing values:   64.19%

JobSat
type:  float64   count:  29126   missing values: 36311   % of missing values:   55.49%

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [5]:
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [6]:
pd.set_option('display.max_rows', 200)

In [7]:
len(df['Country'].value_counts().values.tolist())

185

In [8]:
#let's look at the unique values for the Country column
df['Country'].value_counts().sort_index().head(200)

Country
Afghanistan                                                56
Albania                                                    49
Algeria                                                    77
Andorra                                                    15
Angola                                                     20
Antigua and Barbuda                                         5
Argentina                                                 345
Armenia                                                    58
Australia                                                1260
Austria                                                   791
Azerbaijan                                                 27
Bahamas                                                     4
Bahrain                                                    11
Bangladesh                                                327
Barbados                                                    6
Belarus                                                    97
Belgium                                                   526
Belize                                                      2
Benin                                                      11
Bhutan                                                      3
Bolivia                                                    32
Bosnia and Herzegovina                                     62
Botswana                                                    5
Brazil                                                   1375
Brunei Darussalam                                           3
Bulgaria                                                  319
Burkina Faso                                                4
Burundi                                                     3
Cambodia                                                   22
Cameroon                                                   31
Canada                                                   2104
Cape Verde                                                  5
Central African Republic                                    1
Chad                                                        1
Chile                                                     133
China                                                     406
Colombia                                                  217
Congo, Republic of the...                                   8
Costa Rica                                                 54
Croatia                                                   187
Cuba                                                       23
Cyprus                                                     63
Czech Republic                                            714
Côte d'Ivoire                                              14
Democratic People's Republic of Korea                       2
Democratic Republic of the Congo                            3
Denmark                                                   504
Djibouti                                                    1
Dominica                                                    1
Dominican Republic                                         47
Ecuador                                                    54
Egypt                                                     262
El Salvador                                                19
Equatorial Guinea                                           1
Estonia                                                   110
Ethiopia                                                   60
Fiji                                                        4
Finland                                                   386
France                                                   2110
Gabon                                                       4
Georgia                                                    94
Germany                                                  4947
Ghana                                                      70
Greece                                                    389
Guatemala                                                  41
Guinea                                                      1
Guinea-Bissau                                               2
Guyana                                                      3
Haiti                                                       1
Honduras                                                   16
Hong Kong (S.A.R.)                                        146
Hungary                                                   396
Iceland                                                    31
India                                                    4231
Indonesia                                                 354
Iran, Islamic Republic of...                              411
Iraq                                                       44
Ireland                                                   270
Isle of Man                                                13
Israel                                                    604
Italy                                                    1341
Jamaica                                                    11
Japan                                                     288
Jordan                                                     40
Kazakhstan                                                 81
Kenya                                                     180
Kosovo                                                     18
Kuwait                                                      8
Kyrgyzstan                                                 44
Lao People's Democratic Republic                            4
Latvia                                                    128
Lebanon                                                    46
Lesotho                                                     1
Liberia                                                     4
Libyan Arab Jamahiriya                                      4
Liechtenstein                                               4
Lithuania                                                 183
Luxembourg                                                 40
Madagascar                                                 14
Malawi                                                     12
Malaysia                                                  161
Maldives                                                   16
Mali                                                        2
Malta                                                      29
Mauritania                                                  5
Mauritius                                                  15
Mexico                                                    402
Micronesia, Federated States of...                          1
Monaco                                                      3
Mongolia                                                   10
Montenegro                                                 27
Morocco                                                    98
Mozambique                                                  7
Myanmar                                                    21
Namibia                                                     5
Nauru                                                       1
Nepal                                                     139
Netherlands                                              1449
New Zealand                                               396
Nicaragua                                                  21
Niger                                                       1
Nigeria                                                   305
Nomadic                                                    43
North Korea                                                 3
Norway                                                    450
Oman                                                        8
Pakistan                                                  415
Palestine                                                  15
Panama                                                     18
Papua New Guinea                                            1
Paraguay                                                   39
Peru                                                       75
Philippines                                               196
Poland                                                   1534
Portugal                                                  470
Qatar                                                      15
Republic of Korea                                          57
Republic of Moldova                                        38
Republic of North Macedonia                                36
Romania                                                   439
Russian Federation                                        925
Rwanda                                                     22
Saint Kitts and Nevis                                       1
Samoa                                                       1
San Marino                                                  3
Saudi Arabia                                               56
Senegal                                                     9
Serbia                                                    245
Sierra Leone                                                3
Singapore                                                 177
Slovakia                                                  248
Slovenia                                                  142
Solomon Islands                                             1
Somalia                                                     9
South Africa                                              358
South Korea                                               146
Spain                                                    1123
Sri Lanka                                                 163
Sudan                                                       7
Suriname                                                    5
Swaziland                                                   4
Sweden                                                   1016
Switzerland                                               876
Syrian Arab Republic                                       30
Taiwan                                                    268
Tajikistan                                                  7
Thailand                                                  147
Togo                                                        9
Trinidad and Tobago                                         8
Tunisia                                                    71
Turkey                                                    546
Turkmenistan                                               11
Uganda                                                     39
Ukraine                                                  2672
United Arab Emirates                                      130
United Kingdom of Great Britain and Northern Ireland     3224
United Republic of Tanzania                                28
United States of America                                11095
Uruguay                                                    94
Uzbekistan                                                 62
Venezuela, Bolivarian Republic of...                       69
Viet Nam                                                  296
Yemen                                                      18
Zambia                                                     15
Zimbabwe                                                   26
Name: count, dtype: int64

###Examining the list of unique values we see that we have 'North Korea' and 'Democratic People's Republic of Korea', which are the same. The same happens with 'South Korea'and 'Republic of Korea'.

In [9]:
#Let's now have a look at EdLevel
df['EdLevel'].value_counts().sort_index().head(200)

EdLevel
Associate degree (A.A., A.S., etc.)                                                    1793
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          24942
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       15557
Primary/elementary school                                                              1146
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         2970
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     5793
Some college/university study without earning a degree                                 7651
Something else                                                                          932
Name: count, dtype: int64

###It seems to me that we don't have irrelevant or inconsistent values in this column...

<h5>3.2 Standardize entries in columns like Country or EdLevel by mapping inconsistent values to a consistent format.</h5>

In [10]:
df['Country'] = df['Country'].replace('North Korea', "Democratic People's Republic of Korea")
df['Country'] = df['Country'].replace('South Korea', "Republic of Korea")
df['Country'].value_counts().sort_index().head(200)

Country
Afghanistan                                                56
Albania                                                    49
Algeria                                                    77
Andorra                                                    15
Angola                                                     20
Antigua and Barbuda                                         5
Argentina                                                 345
Armenia                                                    58
Australia                                                1260
Austria                                                   791
Azerbaijan                                                 27
Bahamas                                                     4
Bahrain                                                    11
Bangladesh                                                327
Barbados                                                    6
Belarus                                                    97
Belgium                                                   526
Belize                                                      2
Benin                                                      11
Bhutan                                                      3
Bolivia                                                    32
Bosnia and Herzegovina                                     62
Botswana                                                    5
Brazil                                                   1375
Brunei Darussalam                                           3
Bulgaria                                                  319
Burkina Faso                                                4
Burundi                                                     3
Cambodia                                                   22
Cameroon                                                   31
Canada                                                   2104
Cape Verde                                                  5
Central African Republic                                    1
Chad                                                        1
Chile                                                     133
China                                                     406
Colombia                                                  217
Congo, Republic of the...                                   8
Costa Rica                                                 54
Croatia                                                   187
Cuba                                                       23
Cyprus                                                     63
Czech Republic                                            714
Côte d'Ivoire                                              14
Democratic People's Republic of Korea                       5
Democratic Republic of the Congo                            3
Denmark                                                   504
Djibouti                                                    1
Dominica                                                    1
Dominican Republic                                         47
Ecuador                                                    54
Egypt                                                     262
El Salvador                                                19
Equatorial Guinea                                           1
Estonia                                                   110
Ethiopia                                                   60
Fiji                                                        4
Finland                                                   386
France                                                   2110
Gabon                                                       4
Georgia                                                    94
Germany                                                  4947
Ghana                                                      70
Greece                                                    389
Guatemala                                                  41
Guinea                                                      1
Guinea-Bissau                                               2
Guyana                                                      3
Haiti                                                       1
Honduras                                                   16
Hong Kong (S.A.R.)                                        146
Hungary                                                   396
Iceland                                                    31
India                                                    4231
Indonesia                                                 354
Iran, Islamic Republic of...                              411
Iraq                                                       44
Ireland                                                   270
Isle of Man                                                13
Israel                                                    604
Italy                                                    1341
Jamaica                                                    11
Japan                                                     288
Jordan                                                     40
Kazakhstan                                                 81
Kenya                                                     180
Kosovo                                                     18
Kuwait                                                      8
Kyrgyzstan                                                 44
Lao People's Democratic Republic                            4
Latvia                                                    128
Lebanon                                                    46
Lesotho                                                     1
Liberia                                                     4
Libyan Arab Jamahiriya                                      4
Liechtenstein                                               4
Lithuania                                                 183
Luxembourg                                                 40
Madagascar                                                 14
Malawi                                                     12
Malaysia                                                  161
Maldives                                                   16
Mali                                                        2
Malta                                                      29
Mauritania                                                  5
Mauritius                                                  15
Mexico                                                    402
Micronesia, Federated States of...                          1
Monaco                                                      3
Mongolia                                                   10
Montenegro                                                 27
Morocco                                                    98
Mozambique                                                  7
Myanmar                                                    21
Namibia                                                     5
Nauru                                                       1
Nepal                                                     139
Netherlands                                              1449
New Zealand                                               396
Nicaragua                                                  21
Niger                                                       1
Nigeria                                                   305
Nomadic                                                    43
Norway                                                    450
Oman                                                        8
Pakistan                                                  415
Palestine                                                  15
Panama                                                     18
Papua New Guinea                                            1
Paraguay                                                   39
Peru                                                       75
Philippines                                               196
Poland                                                   1534
Portugal                                                  470
Qatar                                                      15
Republic of Korea                                         203
Republic of Moldova                                        38
Republic of North Macedonia                                36
Romania                                                   439
Russian Federation                                        925
Rwanda                                                     22
Saint Kitts and Nevis                                       1
Samoa                                                       1
San Marino                                                  3
Saudi Arabia                                               56
Senegal                                                     9
Serbia                                                    245
Sierra Leone                                                3
Singapore                                                 177
Slovakia                                                  248
Slovenia                                                  142
Solomon Islands                                             1
Somalia                                                     9
South Africa                                              358
Spain                                                    1123
Sri Lanka                                                 163
Sudan                                                       7
Suriname                                                    5
Swaziland                                                   4
Sweden                                                   1016
Switzerland                                               876
Syrian Arab Republic                                       30
Taiwan                                                    268
Tajikistan                                                  7
Thailand                                                  147
Togo                                                        9
Trinidad and Tobago                                         8
Tunisia                                                    71
Turkey                                                    546
Turkmenistan                                               11
Uganda                                                     39
Ukraine                                                  2672
United Arab Emirates                                      130
United Kingdom of Great Britain and Northern Ireland     3224
United Republic of Tanzania                                28
United States of America                                11095
Uruguay                                                    94
Uzbekistan                                                 62
Venezuela, Bolivarian Republic of...                       69
Viet Nam                                                  296
Yemen                                                      18
Zambia                                                     15
Zimbabwe                                                   26
Name: count, dtype: int64

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [11]:
#let's first have a look on the unique values for this column
print(len(df['Country'].value_counts().values.tolist()))
df['Employment'].value_counts().head(200)

183

Employment
Employed, full-time                                                                                                                                                                                                     39041
Independent contractor, freelancer, or self-employed                                                                                                                                                                     4846
Student, full-time                                                                                                                                                                                                       4709
Employed, full-time;Independent contractor, freelancer, or self-employed                                                                                                                                                 3557
Not employed, but looking for work                                                                                                                                                                                       2341
Employed, part-time                                                                                                                                                                                                      1266
Student, full-time;Employed, part-time                                                                                                                                                                                   1115
Employed, full-time;Student, full-time                                                                                                                                                                                    897
Employed, full-time;Student, part-time                                                                                                                                                                                    839
Student, full-time;Not employed, but looking for work                                                                                                                                                                     686
Not employed, and not looking for work                                                                                                                                                                                    633
Student, part-time;Employed, part-time                                                                                                                                                                                    558
I prefer not to say                                                                                                                                                                                                       546
Retired                                                                                                                                                                                                                   525
Student, part-time                                                                                                                                                                                                        494
Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                                                                                  401
Not employed, but looking for work;Independent contractor, freelancer, or self-employed                                                                                                                                   383
Student, full-time;Independent contractor, freelancer, or self-employed                                                                                                                                                   375
Student, full-time;Not employed, and not looking for work                                                                                                                                                                 311
Employed, full-time;Employed, part-time                                                                                                                                                                                   212
Employed, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                                                              184
Not employed, but looking for work;Student, part-time                                                                                                                                                                     141
Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time                                                                                                                               139
Independent contractor, freelancer, or self-employed;Student, part-time                                                                                                                                                   131
Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                                                               122
Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed                                                                                                                                92
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed                                                                                                                 86
Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                                                                                                63
Independent contractor, freelancer, or self-employed;Not employed, and not looking for work                                                                                                                                58
Employed, full-time;Not employed, but looking for work                                                                                                                                                                     52
Not employed, and not looking for work;Student, part-time                                                                                                                                                                  51
Student, full-time;Student, part-time                                                                                                                                                                                      51
Independent contractor, freelancer, or self-employed;Retired                                                                                                                                                               51
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time                                                                                                                 46
Not employed, but looking for work;Not employed, and not looking for work                                                                                                                                                  40
Employed, full-time;Student, full-time;Employed, part-time                                                                                                                                                                 38
Not employed, but looking for work;Employed, part-time                                                                                                                                                                     27
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                                                23
Not employed, and not looking for work;Retired                                                                                                                                                                             17
Student, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work                                                                                                             17
Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time;Employed, part-time;Retired       13
Employed, full-time;Retired                                                                                                                                                                                                13
Student, full-time;Not employed, but looking for work;Student, part-time                                                                                                                                                   12
Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                                                                            11
Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time                                                                                                                                 11
Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed                                                                                                                11
Employed, full-time;Student, part-time;Employed, part-time                                                                                                                                                                  9
Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired                                                                                                                         9
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Retired                                                                                                                             9
Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                                                                              9
Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                                             8
Student, full-time;Not employed, but looking for work;Employed, part-time                                                                                                                                                   8
Employed, part-time;Retired                                                                                                                                                                                                 8
Student, full-time;Not employed, and not looking for work;Student, part-time                                                                                                                                                8
Not employed, but looking for work;Student, part-time;Employed, part-time                                                                                                                                                   7
Student, full-time;Student, part-time;Employed, part-time                                                                                                                                                                   7
Employed, full-time;Student, full-time;Student, part-time;Employed, part-time                                                                                                                                               6
Student, full-time;Not employed, but looking for work;Not employed, and not looking for work                                                                                                                                6
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work                                                                                              5
Not employed, but looking for work;Retired                                                                                                                                                                                  5
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                              5
Independent contractor, freelancer, or self-employed;Employed, part-time;Retired                                                                                                                                            5
Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                                             5
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time                                                                                               5
Student, part-time;Retired                                                                                                                                                                                                  4
Employed, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time                                                      4
Independent contractor, freelancer, or self-employed;Student, part-time;Retired                                                                                                                                             4
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                                                              4
Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time                                                                                                              4
Not employed, and not looking for work;Employed, part-time                                                                                                                                                                  3
Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                       2
Employed, full-time;Not employed, and not looking for work                                                                                                                                                                  2
Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Employed, part-time                                                                                         2
Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work                                                                                                             2
Employed, full-time;Student, full-time;Student, part-time                                                                                                                                                                   2
Employed, full-time;Student, full-time;Not employed, but looking for work                                                                                                                                                   2
Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Retired                                                                                      2
Employed, full-time;Not employed, but looking for work;Employed, part-time                                                                                                                                                  2
Employed, full-time;Student, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Employed, part-time                                                                                          2
Not employed, but looking for work;Not employed, and not looking for work;Student, part-time                                                                                                                                2
Not employed, but looking for work;Student, part-time;Retired                                                                                                                                                               2
Employed, full-time;Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Employed, part-time                                                                          2
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time                                                        2
Student, full-time;Student, part-time;Retired                                                                                                                                                                               2
Student, full-time;Not employed, and not looking for work;Employed, part-time                                                                                                                                               2
Student, full-time;Not employed, but looking for work;Retired                                                                                                                                                               1
Employed, full-time;Independent contractor, freelancer, or self-employed;Student, part-time;Retired                                                                                                                         1
Student, full-time;Not employed, but looking for work;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work                                                                           1
Student, full-time;Not employed, but looking for work;Not employed, and not looking for work;Student, part-time                                                                                                             1
Employed, full-time;Independent contractor, freelancer, or self-employed;Not employed, and not looking for work;Student, part-time                                                                                          1

In [12]:
#let's determine the original unique options in the survey
all_options = df['Employment'].dropna().str.split(';').explode().unique()
print(all_options)

['Employed, full-time' 'Student, full-time'
 'Not employed, but looking for work'
 'Independent contractor, freelancer, or self-employed'
 'Not employed, and not looking for work' 'Student, part-time'
 'Employed, part-time' 'I prefer not to say' 'Retired']

In [13]:
#let's encode creating a boolean column for each original unique value 
for et in all_options:
    df[et] = df['Employment'].str.contains(et, na=False)
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSat,"Employed, full-time","Student, full-time","Not employed, but looking for work","Independent contractor, freelancer, or self-employed","Not employed, and not looking for work","Student, part-time","Employed, part-time",I prefer not to say,Retired
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,True,False,False,False,False,False,False,False,False
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,True,False,False,False,False,False,False,False,False
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,True,False,False,False,False,False,False,False,False
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,False,True,False,False,False,False,False,False,False
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,False,True,False,False,False,False,False,False,False

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [14]:
missing_values = df.isnull()
missing_values.sum().sort_values(ascending=False)

AINextMuch less integrated                              64289
AINextLess integrated                                   63082
AINextNo change                                         52939
AINextMuch more integrated                              51999
EmbeddedAdmired                                         48704
EmbeddedWantToWorkWith                                  47837
EmbeddedHaveWorkedWith                                  43223
ConvertedCompYearly                                     42002
AIToolNot interested in Using                           41023
AINextMore integrated                                   41009
Knowledge_9                                             37802
Frequency_3                                             37727
Knowledge_8                                             37679
ProfessionalTech                                        37673
Knowledge_7                                             37659
Knowledge_6                                             37573
Knowledge_5                                             37557
Knowledge_2                                             37416
Knowledge_4                                             37407
Knowledge_3                                             37342
Frustration                                             37186
Frequency_2                                             37073
Frequency_1                                             37068
ProfessionalCloud                                       36946
Knowledge_1                                             36773
ProfessionalQuestion                                    36630
TimeAnswering                                           36593
Industry                                                36579
TimeSearching                                           36526
JobSat                                                  36311
JobSatPoints_1                                          36113
JobSatPoints_4                                          36044
JobSatPoints_5                                          36026
JobSatPoints_11                                         35992
JobSatPoints_7                                          35989
JobSatPoints_6                                          35987
JobSatPoints_10                                         35987
JobSatPoints_8                                          35981
JobSatPoints_9                                          35981
MiscTechAdmired                                         35841
WorkExp                                                 35779
ICorPM                                                  35636
AIToolInterested in Using                               34746
PlatformAdmired                                         34060
MiscTechWantToWorkWith                                  32473
CompTotal                                               31697
PlatformWantToWorkWith                                  30905
WebframeAdmired                                         30494
AIToolCurrently Using                                   30365
AISearchDevAdmired                                      29894
AISearchDevWantToWorkWith                               28736
AIBen                                                   28543
AIComplex                                               28416
OfficeStackAsyncAdmired                                 28233
AIAcc                                                   28135
AIChallenges                                            27906
WebframeWantToWorkWith                                  26902
DatabaseAdmired                                         26880
OfficeStackAsyncWantToWorkWith                          26471
MiscTechHaveWorkedWith                                  25994
TechDoc                                                 24540
AIEthics                                                23889
PlatformHaveWorkedWith                                  23071
DatabaseWantToWorkWith                                  22879
BuildvsBuy                                              22079
TechEndorse                                             21769
ToolsTechAdmired                                        21440
AISearchDevHaveWorkedWith                               20984
TBranch                                                 20960
AIThreat                                                20748
OfficeStackSyncAdmired                                  20725
WebframeHaveWorkedWith                                  20276
BuyNewTool                                              20256
SOPartFreq                                              20200
AISent                                                  19564
ToolsTechWantToWorkWith                                 19353
Currency                                                18753
OfficeStackSyncWantToWorkWith                           18726
PurchaseInfluence                                       18031
OrgSize                                                 17957
OfficeStackAsyncHaveWorkedWith                          17344
LearnCodeOnline                                         16200
DatabaseHaveWorkedWith                                  15183
NEWCollabToolsAdmired                                   14726
LanguageAdmired                                         14565
YearsCodePro                                            13827
NEWCollabToolsWantToWorkWith                            13350
ToolsTechHaveWorkedWith                                 12955
OpSysProfessional use                                   12464
CodingActivities                                        10971
RemoteWork                                              10631
OfficeStackSyncHaveWorkedWith                            9892
LanguageWantToWorkWith                                   9685
SurveyLength                                             9255
SurveyEase                                               9199
NEWCollabToolsHaveWorkedWith                             7845
OpSysPersonal use                                        7263
Country                                                  6507
SOHow                                                    6475
SOComm                                                   6274
DevType                                                  5992
SOVisitFreq                                              5901
SOAccount                                                5877
LanguageHaveWorkedWith                                   5692
YearsCode                                                5568
NEWSOSites                                               5151
LearnCode                                                4949
EdLevel                                                  4653
AISelect                                                 4530
ResponseId                                                  0
Employment                                                  0
Age                                                         0
Check                                                       0
MainBranch                                                  0
Employed, full-time                                         0
Student, full-time                                          0
Not employed, but looking for work                          0
Independent contractor, freelancer, or self-employed        0
Not employed, and not looking for work                      0
Student, part-time                                          0
Employed, part-time                                         0
I prefer not to say                                         0
Retired                                                     0
dtype: int64

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [15]:
#let's replace by the median
CCY_median = df['ConvertedCompYearly'].median()
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].replace(np.nan, CCY_median)
df['ConvertedCompYearly'].isnull().sum()

np.int64(0)

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [16]:
#let's see which is the most frequent value for RemoteWork
df['RemoteWork'].value_counts()

RemoteWork
Hybrid (some remote, some in-person)    23015
Remote                                  20831
In-person                               10960
Name: count, dtype: int64

In [17]:
#impute most frequent value to RemoteWork
df['RemoteWork'] = df['RemoteWork'].replace(np.nan, 'Hybrid (some remote, some in-person)')
df['RemoteWork'].isnull().sum()

np.int64(0)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [18]:
#let's create a new column with ConvertedCompYearly normalized; we want to preserve the original column to deal with it later
comp_range = df['ConvertedCompYearly'].max() - df['ConvertedCompYearly'].min()
df['ConvertedCompYearly_MinMax'] = (df['ConvertedCompYearly'] - df['ConvertedCompYearly'].min() ) / comp_range
df[['ConvertedCompYearly_MinMax']].head()

   ConvertedCompYearly_MinMax
0                    0.003998
1                    0.003998
2                    0.003998
3                    0.003998
4                    0.003998

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [19]:
## We will use natural logarithm and create a new column
df['ConvertedCompYearly_log'] = np.log(df['ConvertedCompYearly'])
df[['ConvertedCompYearly_log']].head()

   ConvertedCompYearly_log
0                11.082143
1                11.082143
2                11.082143
3                11.082143
4                11.082143

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [20]:
#let's first see if we have missing values in the YearsCodePro column
df['YearsCodePro'].isnull().sum()

np.int64(13827)

In [21]:
#we will not deal with the missing values here, we will preserve them to be analyzed later...
df['YearsCodePro'].unique()

array([nan, '17', '27', '7', '11', '25', '12', '10', '3',
       'Less than 1 year', '18', '37', '15', '20', '6', '2', '16', '8',
       '14', '4', '45', '1', '24', '29', '5', '30', '26', '9', '33', '13',
       '35', '23', '22', '31', '19', '21', '28', '34', '32', '40', '50',
       '39', '44', '42', '41', '36', '38', 'More than 50 years', '43',
       '47', '48', '46', '49'], dtype=object)

In [22]:
#lets define a function to assign the experience levels
def exp_level(code_years_pro):
    exp_levels = {1: 'Trainee', 6: 'Junior', 11: 'Full', 21: 'Senior', 35: 'Expert', 100: 'Consultant'}

    if pd.isna(code_years_pro):
        return np.nan
    if code_years_pro == 'Less than 1 year':
        return 'Trainee'
    if code_years_pro == 'More than 50 years':
        return 'Consultant'

    try:
        years = float(code_years_pro)
    except (ValueError, TypeError):
        return np.nan

    for limit, exp in exp_levels.items():
        if years < limit:
            return exp

In [23]:
#let's create the new column
df['ExperienceLevel'] = df['YearsCodePro']. apply(exp_level)
df[['YearsCodePro', 'ExperienceLevel']].head()

  YearsCodePro ExperienceLevel
0          NaN             NaN
1           17          Senior
2           27          Expert
3          NaN             NaN
4          NaN             NaN

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.